import AppKit
import CryptoKit

// MARK: - Clipboard history
// macOS has no "something was copied" event, so this checks the pasteboard's change counter
// every 0.5 s and only reads the pasteboard when that number moves.

struct ClipItem: Identifiable, Codable, Equatable {
    enum Kind: String, Codable { case text, rich, link, image, files }

    var id = UUID()
    var kind: Kind
    var date: Date
    var pinned = false
    /// Identity for "copied the same thing again" (a hash, never the content itself).
    var key: String

    var plain: String?            // text, rich (plain version), link
    var rtf: Data?                // rich
    var html: Data?               // rich
    var imageData: Data?          // image, original bytes
    var imageType: String?        // pasteboard type of imageData
    var thumbnail: Data?          // image, small PNG
    var imageSize: CGSize?
    var files: [String]?          // file paths

    var imageBytes: Int { imageData?.count ?? 0 }

    /// One-line-ish label for the list.
    var title: String {
        switch kind {
        case .text, .rich: String((plain ?? "").prefix(400)).trimmingCharacters(in: .whitespacesAndNewlines)
        case .link: URL(string: plain ?? "")?.host ?? (plain ?? "")
        case .image: "Image" + (imageSize.map { " \(Int($0.width))\u{00D7}\(Int($0.height))" } ?? "")
        case .files:
            (files?.count ?? 0) == 1
                ? URL(fileURLWithPath: files![0]).lastPathComponent
                : "\(files?.count ?? 0) files"
        }
    }
}

@MainActor
final class ClipboardStore: ObservableObject {
    static let historyLimit = 30
    static let pinLimit = 10
    /// Full images in the (unpinned) history: 10 MB in total, oldest dropped first.
    static let imageBudget = 10 * 1024 * 1024
    /// Pinned images are kept for good (and saved to disk), so they get their own cap.
    static let pinnedImageBudget = 20 * 1024 * 1024
    /// Bigger than this and an image isn't kept at all.
    static let maxImage = 10 * 1024 * 1024
    /// Formatting (RTF / HTML) bigger than this is dropped; the plain text is still kept.
    static let maxFormatting = 1024 * 1024
    static let maxTextLength = 200_000

    /// Pinned items first (in pin order), then the rest newest first.
    @Published private(set) var items: [ClipItem] = []
    @Published private(set) var pausedUntil: Date?

    /// Called after something new is copied (for the optional nod).
    var onCopy: (() -> Void)?

    private let pasteboard: NSPasteboard
    private var lastChange: Int
    private var timer: Timer?

    var isPaused: Bool { (pausedUntil ?? .distantPast) > Date() }

    /// Decoded thumbnails, so the list doesn't re-decode PNGs on every redraw.
    private var previewCache: [ClipItem.ID: NSImage] = [:]

    func thumbnail(for item: ClipItem) -> NSImage? {
        if let cached = previewCache[item.id] { return cached }
        guard let data = item.thumbnail, let image = NSImage(data: data) else { return nil }
        previewCache[item.id] = image
        return image
    }

    /// Password managers: copies made while one of these is in front are never recorded.
    private static let secretApps: Set<String> = [
        "com.1password.1password", "com.agilebits.onepassword7", "com.agilebits.onepassword-osx",
        "com.bitwarden.desktop", "com.apple.keychainaccess", "com.apple.Passwords",
        "com.dashlane.dashlanephonefinal", "com.lastpass.LastPass", "org.keepassxc.keepassxc",
        "com.markmcguill.strongbox.mac", "in.sinew.Enpass-Desktop", "com.nordpass.macos.NordPass",
        "me.proton.pass.electron",
    ]

    // Password managers mark secrets with these (nspasteboard.org conventions).
    private static let secretTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
    ]

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
        self.lastChange = pasteboard.changeCount
        load()
    }

    // MARK: Watching

    func setEnabled(_ on: Bool) {
        timer?.invalidate()
        timer = nil
        guard on else {
            // Turning Clipboard History off forgets what it saw (pinned items stay).
            if items.contains(where: { !$0.pinned }) { clearHistory() }
            return
        }
        lastChange = pasteboard.changeCount   // don't import whatever was copied while off
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.check() }
        }
        t.tolerance = 0.2
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func pause(for seconds: TimeInterval) {
        pausedUntil = Date().addingTimeInterval(seconds)
    }

    func resume() {
        pausedUntil = nil
        lastChange = pasteboard.changeCount
    }

    func check() {
        let count = pasteboard.changeCount
        guard count != lastChange else { return }
        lastChange = count
        if isPaused { return }
        pausedUntil = nil
        guard let item = Self.capture(pasteboard) else { return }
        insert(item)
        onCopy?()
    }

    // MARK: Reading the pasteboard

    private static func capture(_ pb: NSPasteboard) -> ClipItem? {
        let types = Set((pb.types ?? []).map(\.rawValue))
        if !types.isDisjoint(with: secretTypes) { return nil }
        // Belt and braces: never record anything copied in a password manager.
        if pb == .general, let app = NSWorkspace.shared.frontmostApplication?.bundleIdentifier,
           secretApps.contains(app) { return nil }
        let now = Date()

        // Files copied in Finder
        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            let paths = urls.map(\.path)
            return ClipItem(kind: .files, date: now, key: hash("files", paths.joined(separator: "\n")), files: paths)
        }

        let string = pb.string(forType: .string)

        // Images (screenshots, "Copy Image"). Prefer PNG, then TIFF.
        if string == nil || string?.isEmpty == true {
            for type in [NSPasteboard.PasteboardType.png, .tiff] {
                if let data = pb.data(forType: type), data.count <= maxImage, let image = NSImage(data: data) {
                    return ClipItem(kind: .image, date: now, key: hash("image", data), imageData: data,
                                    imageType: type.rawValue, thumbnail: thumbnail(image),
                                    imageSize: pixelSize(image))
                }
            }
        }

        guard var text = string, !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
        if text.count > maxTextLength { text = String(text.prefix(maxTextLength)) }

        // A single web address
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmed.contains(where: \.isWhitespace), let url = URL(string: trimmed),
           let scheme = url.scheme?.lowercased(), ["http", "https"].contains(scheme), url.host != nil {
            return ClipItem(kind: .link, date: now, key: hash("text", trimmed), plain: trimmed)
        }

        // Formatted text
        // Huge formatting (a whole web page) isn't worth the memory: keep just the text.
        let rtf = pb.data(forType: .rtf).flatMap { $0.count <= maxFormatting ? $0 : nil }
        let html = pb.data(forType: .html).flatMap { $0.count <= maxFormatting ? $0 : nil }
        if rtf != nil || html != nil {
            return ClipItem(kind: .rich, date: now, key: hash("text", text), plain: text, rtf: rtf, html: html)
        }
        return ClipItem(kind: .text, date: now, key: hash("text", text), plain: text)
    }

    private static func hash(_ prefix: String, _ text: String) -> String { hash(prefix, Data(text.utf8)) }

    private static func hash(_ prefix: String, _ data: Data) -> String {
        prefix + ":" + SHA256.hash(data: data).prefix(12).map { String(format: "%02x", $0) }.joined()
    }

    private static func pixelSize(_ image: NSImage) -> CGSize {
        if let rep = image.representations.first, rep.pixelsWide > 0 {
            return CGSize(width: rep.pixelsWide, height: rep.pixelsHigh)
        }
        return image.size
    }

    private static func thumbnail(_ image: NSImage, max side: CGFloat = 160) -> Data? {
        let s = image.size
        guard s.width > 0, s.height > 0 else { return nil }
        let scale = min(1, side / max(s.width, s.height))
        let size = CGSize(width: max(1, (s.width * scale).rounded()), height: max(1, (s.height * scale).rounded()))
        guard let rep = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: Int(size.width), pixelsHigh: Int(size.height),
                                         bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true, isPlanar: false,
                                         colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0) else { return nil }
        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: rep)
        image.draw(in: CGRect(origin: .zero, size: size))
        NSGraphicsContext.restoreGraphicsState()
        return rep.representation(using: .png, properties: [:])
    }

    // MARK: Adding text dragged onto the notch

    func addDropped(text: String) {
        let fake = NSPasteboard(name: NSPasteboard.Name("NotchPal.drop.\(UUID().uuidString)"))
        fake.clearContents()
        fake.setString(text, forType: .string)
        if let item = Self.capture(fake) { insert(item) }
        fake.releaseGlobally()
    }

    // MARK: Changing the list

    private func insert(_ new: ClipItem) {
        // Copied the same thing again: move it to the top (keeping its pin).
        if let i = items.firstIndex(where: { $0.key == new.key }) {
            var existing = items.remove(at: i)
            existing.date = new.date
            items.insert(existing, at: existing.pinned ? 0 : pinnedCount)
            if existing.pinned { savePinned() }
        } else {
            items.insert(new, at: pinnedCount)
        }
        trim()
        scheduleHistorySave()
    }

    /// Pins or unpins. Returns why it couldn't, or nil if it worked.
    func togglePin(_ id: ClipItem.ID) -> String? {
        guard let i = items.firstIndex(where: { $0.id == id }) else { return nil }
        if !items[i].pinned {
            if pinnedCount >= Self.pinLimit { return "Only \(Self.pinLimit) pins!" }
            let pinnedImages = items.filter(\.pinned).reduce(0) { $0 + $1.imageBytes }
            if pinnedImages + items[i].imageBytes > Self.pinnedImageBudget { return "Too many big pinned images!" }
        }
        var item = items.remove(at: i)
        item.pinned.toggle()
        items.insert(item, at: pinnedCount)   // end of the pinned group, or top of the rest
        trim()
        save()
        return nil
    }

    func remove(_ id: ClipItem.ID) {
        let wasPinned = items.first { $0.id == id }?.pinned == true
        items.removeAll { $0.id == id }
        if wasPinned { savePinned() } else { scheduleHistorySave() }
    }

    /// Clears everything except pinned items, and deletes the saved history file.
    func clearHistory() {
        historySaveTask?.cancel()
        items.removeAll { !$0.pinned }
        previewCache = previewCache.filter { id in items.contains { $0.id == id.key } }
        AppFiles.delete(Self.historyFile)
    }

    private var pinnedCount: Int { items.prefix { $0.pinned }.count }

    private func trim() {
        // Unpinned: newest 30.
        var unpinned = 0
        items.removeAll { item in
            guard !item.pinned else { return false }
            unpinned += 1
            return unpinned > Self.historyLimit
        }
        // Unpinned full images: 10 MB in total, oldest dropped first. (Pinned images have their
        // own cap in togglePin, so they can never crowd out what you just copied.)
        var total = items.filter { !$0.pinned }.reduce(0) { $0 + $1.imageBytes }
        while total > Self.imageBudget,
              let oldest = items.lastIndex(where: { !$0.pinned && $0.imageBytes > 0 }) {
            total -= items[oldest].imageBytes
            items.remove(at: oldest)
        }
        // Forget decoded previews of anything that's gone.
        let ids = Set(items.map(\.id))
        previewCache = previewCache.filter { ids.contains($0.key) }
    }

    // MARK: Putting an item back on the clipboard

    /// Writes the item to the clipboard. `plainOnly` drops formatting (Option-click).
    func write(_ item: ClipItem, plainOnly: Bool = false) {
        pasteboard.clearContents()
        switch item.kind {
        case .text:
            pasteboard.setString(item.plain ?? "", forType: .string)
        case .rich:
            if !plainOnly {
                if let rtf = item.rtf { pasteboard.setData(rtf, forType: .rtf) }
                if let html = item.html { pasteboard.setData(html, forType: .html) }
            }
            pasteboard.setString(item.plain ?? "", forType: .string)
        case .link:
            let s = item.plain ?? ""
            if let url = URL(string: s) { pasteboard.writeObjects([url as NSURL]) }
            pasteboard.setString(s, forType: .string)
        case .image:
            if let data = item.imageData, let type = item.imageType {
                pasteboard.setData(data, forType: NSPasteboard.PasteboardType(type))
            }
        case .files:
            let urls = (item.files ?? []).map { URL(fileURLWithPath: $0) as NSURL }
            pasteboard.writeObjects(urls)
        }
        // Our own write shouldn't show up as a new copy.
        lastChange = pasteboard.changeCount
        if let i = items.firstIndex(where: { $0.id == item.id }), !items[i].pinned {
            var moved = items.remove(at: i)
            moved.date = Date()
            items.insert(moved, at: pinnedCount)
        }
        scheduleHistorySave()
    }

    // MARK: Saving
    // Pinned items are always saved. The rest only when "Remember clipboard history" is on.

    private static let pinnedFile = "clipboard-pinned.json"
    private static let historyFile = "clipboard-history.json"

    // Saving is split so a normal ⌘C never rewrites the pinned file (which can hold images),
    // and history saves (only with "Remember" on) are batched into one write a second later.
    private var historySaveTask: Task<Void, Never>?

    /// Saves everything now (pins changed, a setting changed, or the app is quitting).
    func save() {
        savePinned()
        saveHistory()
    }

    private func savePinned() {
        if let data = try? JSONEncoder().encode(items.filter(\.pinned)) { AppFiles.write(data, to: Self.pinnedFile) }
    }

    private func saveHistory() {
        historySaveTask?.cancel()
        historySaveTask = nil
        if Settings.isOn(Settings.rememberHistory) {
            if let data = try? JSONEncoder().encode(items.filter { !$0.pinned }) { AppFiles.write(data, to: Self.historyFile) }
        } else {
            AppFiles.delete(Self.historyFile)
        }
    }

    private func scheduleHistorySave() {
        guard Settings.isOn(Settings.rememberHistory) else { return }
        historySaveTask?.cancel()
        historySaveTask = Task { @MainActor [weak self] in
            try? await Task.sleep(for: .seconds(1))
            guard !Task.isCancelled else { return }
            self?.saveHistory()
        }
    }

    private func load() {
        let dec = JSONDecoder()
        let pinned = AppFiles.read(Self.pinnedFile).flatMap { try? dec.decode([ClipItem].self, from: $0) } ?? []
        var history: [ClipItem] = []
        if Settings.isOn(Settings.rememberHistory) {
            history = AppFiles.read(Self.historyFile).flatMap { try? dec.decode([ClipItem].self, from: $0) } ?? []
        }
        items = pinned.map { var p = $0; p.pinned = true; return p } + history.map { var h = $0; h.pinned = false; return h }
        trim()
    }
}
